### ISSUE TITLE
java.lang.ClassCastException: com.joooonho.SelectableRoundedImageView$SelectableRoundedCornerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by kHRYSTAL** [pungrue26/SelectableRoundedImageView#10]
BitmapDrawable db = (BitmapDrawable) pic.getDrawable();
        if (db != null)
            return db.getBitmap();
        return null;

**Comment by pungrue26** [comment]
Yes, <code>SelectableRoundedCornerDrawable</code> is not a <code>BitmapDrawable</code>, and casting to it will throw ClassCastException. SelectableRoundedCornerDrawable didn't extend BitmapDrawable in terms of OOD.

Currently, this library doesn't support extracting bitmap object from drawable.

**Comment by kHRYSTAL** [comment]
thank you

**Comment by pungrue26** [comment]
No problem.
