### ISSUE TITLE
giving error while pulling image using glide

### ISSUE THREAD

**Issue by ghost** [pungrue26/SelectableRoundedImageView#11]
``` 
Glide.with(getContext())
                .load(imageUri))
                .placeholder(R.drawable.abc)
                .into(imageView);
```

 java.lang.ClassCastException: android.graphics.drawable.TransitionDrawable cannot be cast to com.joooonho.SelectableRoundedImageView$SelectableRoundedCornerDrawable

**Comment by pungrue26** [comment]
Got it. I'll look into it and leave a comment soon. :)

**Comment by pungrue26** [comment]
I'm sorry for late response.

Currently I'm searching job opportunities, and I spend most of my time preparing coding interview. So, I couldn't have time to look at it. I'll look into this after I got a job. :)

Though, for your information, SelectableRoundedImageView works great with Square's Picasso and Universal Image Loader.

**Comment by invised** [comment]
I had the same issue with LayerDrawable, the problem was in fromDrawable(Drawable, Resources) method, the solution was to comment out this:

	else if (drawable instanceof LayerDrawable) {
		LayerDrawable ld = (LayerDrawable) drawable;
		final int num = ld.getNumberOfLayers();
		for (int i = 0; i < num; i++) {
			Drawable d = ld.getDrawable(i);
			ld.setDrawableByLayerId(ld.getId(i), fromDrawable(d, r));
		}
		return ld;
	}

After fast looking through the code, this piece of code seems to be problematic and redundant. Here you turn every layer to RoundedDrawable, but still return LayerDrawable, whereas next line of code

    Bitmap bm = drawableToBitmap(drawable);

does it all at once. 

Any comments on this?

**Comment by pungrue26** [comment]
I'm sorry, but I just don't have time to think it over these days.

I'll look into this as soon as possible. :)

**Comment by qky1412** [comment]
same issue here

**Comment by jompon** [comment]
me too

**Comment by Seema-Android** [comment]
facing same issue

**Comment by sivan67** [comment]
me too

**Comment by qluojieq** [comment]
works not well

**Comment by qluojieq** [comment]
I found a way  to solve this problem 
Glide.with(context).load(src).**asBitmap().**listener(l).placeholder(loading).into(imageView) 
remmber to add "asBitmap()"

**Comment by pungrue26** [comment]
Great! Thumbs up! :)
2016. 5. 20. 오전 11:16에 "jie.luo" <notifications@github.com>님이 작성:

**Comment by pungrue26** [comment]
Guys, please try asBitmap() like @qluojieq mentioned.
