### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Jarkomg** [pungrue26/SelectableRoundedImageView#12]
SelectableRoundedImageView$SelectableRoundedCornerDrawable.drawableToBitmap(SelectableRoundedImageView.java:387)
SelectableRoundedImageView$SelectableRoundedCornerDrawable.fromDrawable(SelectableRoundedImageView.java:364)
SelectableRoundedImageView.setImageDrawable(SelectableRoundedImageView.java:145)

**Comment by pungrue26** [comment]
Hmm... 

I will look into the code for optimizing. But like I said in other thread, I am looking for a job, and I spend my entire time preparing coding interview these days. I will come back as soon as I get an offer. :)

**Comment by pungrue26** [comment]
Sorry for long waiting. 

I've looked at it, and it's not defect of this class. You may encounter OOM anytime when you deal with <code>Bitmap</code> object even if you use framework's <code>ImageView</code> class. I think you might find this [Managing Bitmap Memory](https://developer.android.com/training/displaying-bitmaps/manage-memory.html) training guide helpful . Also [Allocation Tracker](https://developer.android.com/studio/profile/allocation-tracker-walkthru.html) is another handy tool for monitoring memory usage.

I think this project can be improved with scaling options, but you can still scale <code>Bitmap</code> beforehand, and everything will work ok. :)
