### ISSUE TITLE
The image cannot be showed sometimes when used by Glide 3.7.0

### ISSUE THREAD

**Issue by mikiller** [pungrue26/SelectableRoundedImageView#13]
```
SimpleTarget target = new SimpleTarget<GlideBitmapDrawable>() {
            @Override
            public void onResourceReady(GlideBitmapDrawable resource, GlideAnimation glideAnimation) {

                selectRoundIv.setImageBitmap(resource.getBitmap());
            }
        };

Glide.with(context).load(path).into(target);
```

This is my code for loading url image. The "selectRoundIv" is the object of SelectableRoundedImageView.  It seems worked. But when I set scaleType with centerCrop, there's a problem.  The image cannot be showed, or be showed without corners.

![qq 20160908113755](https://cloud.githubusercontent.com/assets/8773041/18336360/1bc215a0-75b9-11e6-9e3e-f690a3c0afef.png)

This is the effect of this issue.  By the way, the top imageview' url and the top selectableRoundImageView's url are the same.

![qq 20160908114828](https://cloud.githubusercontent.com/assets/8773041/18336485/37cb6f0c-75ba-11e6-9d9a-0e965e74e403.png)
And this is the effect which is image be showed without cornors.

**Comment by pungrue26** [comment]
I'll look into it, and come back soon! :)

**Comment by pungrue26** [comment]
Found the reason, and solution as well!

It seems you are using old version of Glide. <code>GlideBitmapDrawable</code> was replaced with Android framework's <code>BitmapDrawable</code> at [af6e1e8](https://github.com/bumptech/glide/commit/af6e1e8504f874cc7b9117e10534375b4e6b3140) commit which is done about 2 years ago! 


**Reason:**
<code>[GlideBitmapDrawable](https://github.com/bumptech/glide/blob/d7ddcf57b963b2dca559b4b71ccc285965c72f19/library/src/main/java/com/bumptech/glide/load/resource/bitmap/GlideBitmapDrawable.java)</code> class handles drawing itself, so <code>SelectableRoundedImageView</code> loses chance to draw. 

**Solution:**
Don't use <code>GlideBitmapDrawable</code> as <code>RequestListener</code>'s type argument. Use <code>BitmapDrawable</code> class.

```java
Glide.with(this)
        .load(result.images.original.url)
        .thumbnail(thumbnailRequest)
        .listener(new RequestListener<BitmapDrawable>() {
          //...

          @Override
          public boolean onResourceReady(BitmapDrawable resource, Object model, Target<BitmapDrawable> target,
              DataSource dataSource, boolean isFirstResource) {
            // You can use resource as BitmapDrawable!
          }
        })
        .into(imageView);
```

**Comment by mikiller** [comment]
It's very kind of you to help me in resolving the problem. But there's a little pity, the version of Glide on jcenter is only upto 3.7.0. The way which you showed depends on 4.0 on github's library.  So I have to use "asBitmap" to get bitmap and "setImagebitmap” in SimpleTarget and wait for 4.0 on jcenter later.  Anyway, do not use GlideBitmapDrawable, that's right.  Thank you for your help and your SelectableRoundedImageView :)

**Comment by pungrue26** [comment]
No problem! :)
