### ISSUE TITLE
Not work in the ListView.

### ISSUE THREAD

**Issue by sd6352051** [pungrue26/SelectableRoundedImageView#5]

**Comment by pungrue26** [comment]
could you give me details? How can I reproduce the problem?

**Comment by sd6352051** [comment]
The images will deformation when listview sliding,image will be squeezed

**Comment by pungrue26** [comment]
Sorry for late reply. 

I checked it works with 
1) Android framework's ImageView.setImageDrawable() method, and
2) Square's Picasso : with().load().into() method.

but finally I found that it does NOT work with Android Universal Image Loader(https://github.com/nostra13/Android-Universal-Image-Loader). Now I am digging into it to find what went wrong.

So, I want to ask you, 

1) Which image loading library do you use?
2) Can you post the screenshot?
3) Can you share me the source code that doesn't work?

I truly want to improve this library as best as I can. I really appreciate your report. Please help me a little more. Your help would be much appreciated. 

Thanks in advance.

**Comment by sd6352051** [comment]
Sorry, I didn't speak clearly. My English is not good, i use UIL lib,  
this is my list adapter ,i use [androidannotations ][1] and  [Android-PullToRefresh][2]
``` java
@EBean
public class ProductAdapter extends BaseAdapter {
private final ArrayList<ProjectInfo> lists = new ArrayList<ProjectInfo>();
	
	@RootContext
    protected Context context;
	
	public void reloadList(List<ProjectInfo> list) {
        if (!lists.containsAll(list)) {
        	lists.clear();
            lists.addAll(list);
        }
        notifyDataSetChanged();
    }
	public void appendList(List<ProjectInfo> list) {
        if (!lists.containsAll(list)) {
            lists.addAll(list);
        }
        notifyDataSetChanged();
    }
	public int  getListSize() {
		return lists==null?0:lists.size();
	}
    public void clear() {
        lists.clear();
        notifyDataSetChanged();
    }
    public ArrayList<ProjectInfo> getData() {
    	return lists;
	}
    @Override
    public int getCount() {
        return lists.size();
    }

    @Override
    public Object getItem(int position) {
        return lists.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
    	ItemProductList itemview;
        if (convertView == null) {
        	itemview = ItemProductList_.build(context);
        } else {
        	itemview = (ItemProductList) convertView;
        }

        itemview.setData(lists.get(position));
        //setData method  ImageLoader.getInstance().displayImage(imgurl, mImageViewImg, def_options)


        return itemview;
    }
```
Thank you for your kind reply. 

[1]: https://github.com/excilys/androidannotations
[2]: https://github.com/chrisbanes/Android-PullToRefresh

**Comment by pungrue26** [comment]
A thousand time thanks. Also if you are not comfortable with writing in English, you can write in Chinese, because I have a good Chinese friend, so I will ask him to translate it.

I also found a interesting bug. This library doesn't work when convert view is saved and retrieved with setTag(), getTag(). So this library does work when :

if (convertView == null) {
    view = mInflater.inflate(R.layout.list_item_icon_text, parent, false);
} else {
    view = convertView;
}

But this library does NOT work(corners get rounded twice) when :

if (convertView == null) {
	view = inflater.inflate(R.layout.item_list_image, parent, false);
	holder = new ViewHolder();
	holder.text = (TextView) view.findViewById(R.id.text);
	holder.image = (ImageView) view.findViewById(R.id.image);
	view.setTag(holder);
} else {
	holder = (ViewHolder) view.getTag();
}

What a interesting, but nasty, bug.. :( I will find the cause and assassinate it ASAP. 

Once again, I am extremely grateful to your report and kind feedback. Please have a nice day. I will leave another comment when I finish it. :)

**Comment by pungrue26** [comment]
I starred every single projects you open-sourced on github to show my appreciation. 

Have a great day! :)

**Comment by pungrue26** [comment]
Dear sd635205,

I found the reason that caused the problem. Just DO NOT use RoundedBitmapDisplayer or RoundedVignetteBitmapDisplayer when building DisplayImageOptions. Use SimpleBitmapDisplayer or FadeInBitmapDisplayer. See below code.

``` java
options = new DisplayImageOptions.Builder()
				.showImageOnLoading(R.drawable.ic_stub)
				.showImageForEmptyUri(R.drawable.ic_empty)
				.showImageOnFail(R.drawable.ic_error)
				.cacheInMemory(false)
				.cacheOnDisk(false)
				.considerExifParams(false)
//				.displayer(new RoundedBitmapDisplayer(20))
//				Avoid using RoundedBitmapDisplayer. Use SimpleBitmapDisplayer!
				.displayer(new SimpleBitmapDisplayer())
				.build();
```

**Comment by sd6352051** [comment]
Thank you very much  :)

**Comment by pungrue26** [comment]
Dear Tao,

Could you please check my solution works in your application? I checked in my test app, but I want to make sure it.

**Comment by sd6352051** [comment]
worked well :smile:

**Comment by pungrue26** [comment]
Thanks a LOT!!

Have a great day! :)
2015. 2. 13. 오후 12:13에 "李涛 LiTao" <notifications@github.com>님이 작성:

**Comment by KennyGoers** [comment]
Hello,

I've been monitoring the conversation, as I've had a similar problem with
Picasso with one specific image used for the initial start image, that
image is just a centered icon, but when I use it, it distorts it. I will
try to put some code together and a screen shot. It seems like a pretty
specific case.

Kenny

**Comment by pungrue26** [comment]
To kenny,

Ok. Please share me some code, so that I can reproduce your problem. :)

Joonho

**Comment by Vurtex** [comment]
我有一个相同的问题，我使用的图片加载工具是 [novoda-image-loader](https://github.com/novoda/image-loader) 但是我更希望SelectableRoundedImageView做一些修改。

**Comment by pungrue26** [comment]
To Vurtex,

Can you give me more detail? Also please open new issue rather than this one.
