### ISSUE TITLE
在ListView中ImageView会根据当前Item的高度而改变图片的显示高度。

### ISSUE THREAD

**Issue by Vurtex** [pungrue26/SelectableRoundedImageView#7]
在ListView里面，我使用的图片加载工具是 [novoda-image-loader](https://github.com/novoda/image-loader) 但是我更希望SelectableRoundedImageView做一些修改，因为使用[Aquery](https://github.com/Vurtex/AQuery)加载图片也会有相同的问题。

	public class GridAdapter extends BaseAdapter {
		private List<NaiFen> data;
		private Context c;

		public GridAdapter(Context c, List<NaiFen> dataList) {
			this.c = c;
			this.data = dataList;
		}

		@Override
		public int getCount() {
			return 20;
		}

		@Override
		public Object getItem(int arg0) {
			return null;
		}

		@Override
		public long getItemId(int arg0) {
			return 0;
		}

		@Override
		public View getView(int position, View convertView, ViewGroup parent) {
			ViewHolder holder;
			if (null == convertView) {
				holder = new ViewHolder();
				convertView = LayoutInflater.from(c).inflate(
						R.layout.grid_item_layout, null);
				holder.img = (SelectableRoundedImageView) convertView.findViewById(R.id.img);
				holder.title_tv = (TextView) convertView
						.findViewById(R.id.title_tv);
				holder.price_tv = (TextView) convertView
						.findViewById(R.id.price_tv);
				holder.flag_img = (ImageView) convertView
						.findViewById(R.id.flag_img);
				holder.old_price_tv = (TextView) convertView
						.findViewById(R.id.old_price_tv);
				convertView.setTag(holder);
			} else {
				holder = (ViewHolder) convertView.getTag();
			}
			holder.old_price_tv.getPaint()
					.setFlags(Paint.STRIKE_THRU_TEXT_FLAG);
                        loadBigImage(item.getPic_url(), holder.img);
			return convertView;
		}

		static class ViewHolder {
			SelectableRoundedImageView img;
			TextView title_tv;
			ImageView flag_img;
			TextView price_tv;
			TextView old_price_tv;
		}

		protected void loadBigImage(String url, ImageView view) {
		        view.setTag(imageBigTagFactory.build(url, c));
		        imageBigManager.getLoader().load(view);
		}
	}

**Comment by pungrue26** [comment]
Sorry for late response,

It seems like I need to look into novoda-image-loader's source code, but as I mentioned in other thread, I am a bit busy these days, so It can take some time. 

If you are urgent, please consider switching your image loading library to Picasso, or Universal Image Loaders.

Best,
Joonho

**Comment by pungrue26** [comment]
Vurtex,

I am really sorry for late response. But I'm gonna close this issue, because image-loader is now deprecated and unmaintained. 

This library works fine with Android-Universal-Image-Loader, or Picasso, and they are pretty good ones. :)
