### ISSUE TITLE
onClick: color overlay or selectable drawable

### ISSUE THREAD

**Issue by riinav** [pungrue26/SelectableRoundedImageView#8]
Hi,
Do we have any feature to use overlay color or image on clicking on the image?

**Comment by pungrue26** [comment]
Hm.. no this library doesn't support such feature, and I have no plan for it at this moment.

But, you can achieve it with overlapping two SelectableRoundedImageView in a RelativeLayout, and as far as I know that's the way people do.

For example, a sample app, called "Just for us" , showcased by official Android Developer channel in YouTube, used such approach. I captured a screenshot.

![just_for_us_screenshot](https://cloud.githubusercontent.com/assets/4414981/8742016/c01ff79c-2c9b-11e5-86a0-6f8691acd103.png)

video link : https://www.youtube.com/watch?v=aoFdDAAHfGM, 
source code : http://goo.gl/0CEXJa

Below is layout xml for one card :

    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_height="200dp"
        android:layout_width="match_parent">

        <ImageView
            android:id="@+id/image"
            android:layout_alignParentLeft="true"
            android:layout_alignParentTop="true"
            android:layout_height="match_parent"
            android:layout_width="match_parent"
            android:contentDescription="@null"
            android:scaleType="centerCrop"
            android:visibility="invisible"/>

        <LinearLayout
            android:background="@drawable/overlay_bg"
            android:layout_alignParentBottom="true"
            android:layout_alignParentLeft="true"
            android:layout_height="wrap_content"
            android:layout_width="match_parent"
            android:orientation="vertical"
            android:padding="16dp">

            <TextView
                android:id="@+id/title"
                android:layout_height="wrap_content"
                android:layout_width="match_parent"
                android:paddingTop="16dp"
                android:fontFamily="sans-serif-condensed"
                android:textAppearance="?android:textAppearanceLargeInverse"/>

            <TextView
                android:id="@+id/subtitle"
                android:layout_height="wrap_content"
                android:layout_width="match_parent"
                android:maxLines="2"
                android:ellipsize="end"
                android:fontFamily="sans-serif"
                android:textAppearance="?android:textAppearanceSmallInverse"/>

        </LinearLayout>

        <View
            android:id="@+id/touch_layer"
            android:layout_alignParentLeft="true"
            android:layout_alignParentTop="true"
            android:layout_height="match_parent"
            android:layout_width="match_parent"
            android:background="@drawable/touch_layer_bg"/>
    </RelativeLayout>

The last child of RelativeLayout listens for touch event, and change its background color upon it. So, you can put 2 SelectableRoundedImageView in a RelativeLayout, and register listener for outer one. I hope this helps you achieve what you want, and please let me know the result. :)

**Comment by riinav** [comment]
Thanks for the tip, I'll look into it :)

**Comment by pungrue26** [comment]
@riinav 

Sorry for misleading. The solution that I mentioned above has a mistake, and let me correct it.

You should put 1 SelectableRoundedImageView and 1 view in a RelativeLayout, NOT 2 SelectableRoundedImageView. I'll share some sample code.

    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_height="wrap_content"
        android:layout_width="match_parent">

    <com.joooonho.SelectableRoundedImageView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_height="200dp"
            android:layout_width="match_parent"
            app:sriv_left_top_corner_radius="16dip"
            app:sriv_right_top_corner_radius="0dip"
            app:sriv_left_bottom_corner_radius="48dip"
            app:sriv_right_bottom_corner_radius="16dip"
            android:scaleType="centerCrop"/>

        <View
            android:layout_height="200dp"
            android:layout_width="match_parent"
            android:background="@drawable/touch_layer_bg"/>
    </RelativeLayout>

and touch_layer_bg.xml would be :

    <?xml version="1.0" encoding="utf-8"?>
    <selector xmlns:android="http://schemas.android.com/apk/res/android" >    
        <item android:state_pressed="true" android:drawable="@drawable/pressed"></item>
        <item android:drawable="@drawable/normal"></item>
    </selector>

prssed.xml :

    <?xml version="1.0" encoding="utf-8"?>
    <shape xmlns:android="http://schemas.android.com/apk/res/android" >
        <corners
            android:bottomLeftRadius="16dp"
            android:bottomRightRadius="48dp"
            android:topLeftRadius="16dp"
            android:topRightRadius="0dp" />
        <solid android:color="#80000000" />
    </shape>

normal.xml :

    <?xml version="1.0" encoding="utf-8"?>
    <shape xmlns:android="http://schemas.android.com/apk/res/android" >
        <corners
            android:bottomLeftRadius="48dp"
            android:bottomRightRadius="16dp"
            android:topLeftRadius="16dp"
            android:topRightRadius="0dp" />
        <solid android:color="@android:color/transparent" />
    </shape>


Finally, you can set OnClickListener on outer view. I think this will do the trick. :)
