### ISSUE TITLE
When I set SelectableRoundedImageView ,outside CardView cardCornerRadius can't working

### ISSUE THREAD

**Issue by kHRYSTAL** [pungrue26/SelectableRoundedImageView#9]
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     xmlns:tools="http://schemas.android.com/tools"
     android:id="@+id/news_card_view"
     android:layout_width="match_parent"
     android:layout_height="68dp"
     app:cardBackgroundColor="#3f3f3f"
     app:cardCornerRadius="8dp"
     app:contentPadding ="0dp"
     app:cardPreventCornerOverlap="false">
    <RelativeLayout
        android:background="#3f3f3f"
        android:id="@+id/news_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingRight="@dimen/small_padding">
        <com.joooonho.SelectableRoundedImageView
             app:sriv_left_top_corner_radius="8dp"
             app:sriv_right_top_corner_radius="0dip"
             app:sriv_left_bottom_corner_radius="8dp"
             app:sriv_right_bottom_corner_radius="0dp"
            android:background="@drawable/news_image_bg"
            android:id="@+id/pic"
            android:layout_width="68dp"
            android:layout_height="68dp"
            android:layout_marginRight="@dimen/default_padding"
            android:scaleType="centerCrop" />
       </RelativeLayout>
</android.support.v7.widget.CardView>

-------------------------------------
when i do like this ,cardview's shape is rectangle

**Comment by pungrue26** [comment]
Sorry kHRYSTAL , but I can't understand this issue.

First of all, your xml is not well formatted. I can better understand if you can upload well-formatted xml file.
Secondly, sharing your java code about <code>CardView</code> would be helpful as well.
